# Generated by Django 3.2.4 on 2021-06-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Person',
        ),
    ]
